// // import "./globals.css";
// // import Header from "@/components/navbar-components/Header";
// // import Sidebar from "../components/sidebar/Sidebar";

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en" className="h-full">
// //       <body className="flex flex-col h-full bg-slate-50">
// //         <Header />
// //         <div className="flex flex-1 overflow-hidden"> {/* min-h: Ensure it takes full height below header (assuming header is ~64px tall) */}
// //           {/* Sidebar - Visible on medium and larger screens */}
// //           <aside className="hidden md:block w-60 bg-slate-900 text-fuchsia-50 p-4 shadow-lg border-r border-slate-700">
// //             <Sidebar />
// //           </aside>

// //           {/* Main Content Area - Takes remaining space */}
// //           <main className="flex-1 p-4 bg-gray-50 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]"> {/* Added overflow-auto for content scrolling */}
// //             {children} {/* This is where your page content will be rendered */}
// //           </main>
// //         </div>
// //         {/* {children} */}
// //       </body>
// //     </html>
// //   );
// // }

// // app/layout.jsx
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import Header from "@/components/navbar-components/Header"; // Your Header component
// // import Sidebar from "../components/sidebar/Sidebar"; // Your Sidebar component

// // // Removed Supabase server client imports

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "PeerFlow",
// //   description: "Seamless Peer-to-Peer Learning",
// // };

// // // RootLayout is now a standard Server Component, no async data fetching here for user
// // export default function RootLayout({ children }) {
// //   // --- SIMULATED USER STATE ---
// //   // To test "logged in" state, uncomment the dummyUser object below.
// //   // To test "logged out" state, keep user as null.
// //   // const user = null; // Default: logged out

// //   // Uncomment this block to simulate a logged-in user:
// //   const dummyUser = {
// //     id: 'simulated-user-123',
// //     email: 'test@example.com',
// //     fullName: 'Simulated User',
// //     profilePic: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser', // Example profile pic
// //     user_metadata: { // Mimic Supabase user_metadata structure
// //       full_name: 'Simulated User',
// //       avatar_url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser',
// //     }
// //   };
// //   const user = dummyUser; // Set user to dummyUser to simulate logged in

// //   return (
// //     <html lang="en" className="h-full">
// //       <body className={`${inter.className} flex flex-col h-full bg-slate-50`}>
// //         {/* Pass the simulated user object to the Header */}
// //         <Header user={user} />

// //         <div className="flex flex-1 overflow-hidden">
// //           <aside className="hidden md:block w-64 bg-slate-900 text-fuchsia-50 p-4 shadow-lg border-r border-slate-700">
// //             <Sidebar />
// //           </aside>

// //           <main className="flex-1 p-4 bg-gray-50 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
// //             {children}
// //           </main>
// //         </div>
// //       </body>
// //     </html>
// //   );
// // }

// // app/layout.jsx
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/navbar-components/Header";
// import Sidebar from "../components/sidebar/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "PeerFlow",
//   description: "Seamless Peer-to-Peer Learning",
// };

// // Add 'modal' as a prop to RootLayout
// export default function RootLayout({ children, modal }) { // <-- ADDED 'modal' PROP
//   // --- SIMULATED USER STATE ---
//   // To test "logged in" state, uncomment the dummyUser object below.
//   // To test "logged out" state, keep user as null.
//   const user = null; // Default: logged out

//   /*
//   // Uncomment this block to simulate a logged-in user:
//   const dummyUser = {
//     id: 'simulated-user-123',
//     email: 'test@example.com',
//     fullName: 'Simulated User',
//     profilePic: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser',
//     user_metadata: {
//       full_name: 'Simulated User',
//       avatar_url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser',
//     }
//   };
//   const user = dummyUser; // Set user to dummyUser to simulate logged in
//   */

//   return (
//     <html lang="en" className="h-full">
//       <body className={`${inter.className} flex flex-col h-full bg-slate-50`}>
//         <Header user={user} />

//         <div className="flex flex-1 overflow-hidden">
//           <aside className="hidden md:block w-64 bg-slate-900 text-fuchsia-50 p-4 shadow-lg border-r border-slate-700">
//             <Sidebar />
//           </aside>

//           <main className="flex-1 p-4 bg-gray-50 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
//             {children}
//           </main>
//         </div>

//         {/* NEW: Render the modal slot here */}
//         {modal}
//       </body>
//     </html>
//   );
// }

// app/layout.jsx
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/navbar-components/Header";
import Sidebar from "../components/sidebar/Sidebar";
import { createServerSupabaseClient } from "@/lib/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PeerFlow",
  description: "Seamless Peer-to-Peer Learning",
};

// REMOVED 'modal' PROP
export default async function RootLayout({ children }) {
  // --- SIMULATED USER STATE ---
  // const user = null; // Default: logged out
  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // const user = user?.user || null;

  // Uncomment this block to simulate a logged-in user:
  // const dummyUser = {
  //   id: 'simulated-user-123',
  //   email: 'test@example.com',
  //   fullName: 'Simulated User',
  //   profilePic: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser',
  //   user_metadata: {
  //     full_name: 'Simulated User',
  //     avatar_url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=SimulatedUser',
  //   }
  // };
  // const user = dummyUser; // Set user to dummyUser to simulate logged in

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} flex flex-col h-full bg-slate-50`}>
        <Header user={user} />

        <div className="flex flex-1 overflow-hidden">
          <aside className="hidden md:block w-64 bg-slate-900 text-fuchsia-50 p-4 shadow-lg border-r border-slate-700">
            <Sidebar />
          </aside>

          <main className="flex-1 p-4 bg-gray-50 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
            {children}
          </main>
        </div>

        {/* REMOVED: {modal} */}
      </body>
    </html>
  );
}
